defaults:
  - dp3_baseline
  - _self_
      
mixed_precision: "bf16"
output_dir: "checkpoints/dp34thanos_${train_dataset.task}_None_1v_3d"

train_dataset:
  task: place_cube_limit_3d
  demo: None
  root: datasets/thanos/${train_dataset.task}
  repo_id: D-robotics/${train_dataset.task}
  # npy_feature_keys: null
  # dataset_metadata:
  #   root: ${train_dataset.root}
  #   repo_id: ${train_dataset.repo_id}