defaults:
  - vodp_base
  - _self_

shape_meta:
  obs:
    head_cam:
      shape: ${image_shape}
      type: rgb
    front_cam:
      shape: ${image_shape}
      type: rgb
    agent_pos:
      shape: [14]
      type: low_dim
      
mixed_precision: "bf16"
output_dir: "checkpoints/mvdp_${train_dataset.task}_${train_dataset.demo}_23d_3f"

model:
  obs_encoder:
    out_channels: 526
    # rgb_key: ["head_cam", "front_cam"]
    emvis_config:
      dim_2d: null
      dim_3d_keys: ['frame', 'global']
      load_vggt_heads: true
      load_vggt_pretrain: true
      vggt_model_path: pretrained/VGGT-1B/model.pt
      interpolate: 'bilinear'
      mlp_ratio: 1.0
      drop_p: 0.0
      ft_heads: []
      ft_layer_idx: []
      intermediate_layer_idx: [23]
      seq_as_view: False
      only_first_view: True
      injector_config:
        fuse_2d: True
        fuse_3d: False
        ffn_layer_num: 1
        dim_out: 1024
      model_adapter_config:
        target: ResNetAdapter
        shape_out: [1, 1]
        dim_out: 512
        conv_num: 3
      mv_fuser_config: {}