defaults:
  - dp_baseline
  - _self_



model:
  obs_encoder:
    _target_: drrm.models.policy.diffusion_policy.multi_image_obs_encoder_emvis_exp1.MultiImageObsEncoderEmvisExp1
    out_channels: 526
    emvis_config:
      embed_dim: 2048
      load_vggt_pretrain: true
      load_vggt_heads: True
      vggt_model_path: /root/data/projects/embodiedai/RoboticsManipulation/RoboticsManipulation/checkpoints/VGGT-1B/model.pt
      use_token_adapter: true
      mlp_ratio: 4.0
      intermediate_layer_idx: [11]
      # injector_config:
      #   token_align: False
      #   fusion_method: "gate"
      #   norm_layers: ['attn', 'ffn', 'fusion']
      #   boardcast_block_num: 1
      model_adapter_config:
        image_shape: [240, 320]
        target_shape: [1, 1]
        target_dim: 512

train_dataset:
  root: /root/data/projects/embodiedai/RoboticsManipulation/RoboticsManipulation/data/lerobot/dual_bottles_pick_hard_D435_drrm
  repo_id: D-robotics/dual_bottles_pick_hard_D435_drrm
  npy_feature_keys: ['spatial_tokens_11', 'image_tokens_pos']
  dataset_metadata:
    root: /root/data/projects/embodiedai/RoboticsManipulation/RoboticsManipulation/data/lerobot/dual_bottles_pick_hard_D435_drrm
    repo_id: D-robotics/dual_bottles_pick_hard_D435_drrm