defaults:
  - dp_baseline
  - _self_



model:
  obs_encoder:
    _target_: drrm.models.policy.diffusion_policy.multi_image_obs_encoder_emvis_exp1.MultiImageObsEncoderEmvisExp1
    out_channels: 526
    emvis_config:
      dim_2d: None
      load_vggt_heads: false
      load_vggt_pretrain: true
      vggt_model_path: pretrained/VGGT-1B/model.pt
      mlp_ratio: 2.0
      intermediate_layer_idx: [4, 11, 17, 23]
      interpolate: 'bicubic'
      injector_config:
        proj_type: "Linear"  # 'Linear' 'MLP' 'Nonlinear'
        fuse_2d: False
        fusion_method: "weight" # weight, gate, dim, mlp
        boardcast_block_num: 1
      model_adapter_config:
        shape_out: [1, 1]
        dim_out: 512
  out_channels: ${model.obs_encoder.out_channels}

train_dataset:
  root: datasets/lerobot/dual_bottles_pick_hard_D435
  repo_id: D-robotics/dual_bottles_pick_hard_D435
  npy_feature_keys: null
  dataset_metadata:
    root: ${train_dataset.root}
    repo_id: ${train_dataset.repo_id}