defaults:
  - dp_baseline
  - _self_

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    head_cam:
      shape: ${image_shape}
      type: rgb
    front_cam:
      shape: ${image_shape}
      type: rgb
    # left_cam:
    #   shape: *image_shape
    #   type: rgb
    # right_cam:
    #   shape: *image_shape
    #   type: rgb
    agent_pos:
      shape: [14]
      type: low_dim

model:
  obs_encoder:
    _target_: drrm.models.policy.diffusion_policy.multi_image_obs_encoder_emvis_exp1.MultiImageObsEncoderEmvisExp1
    out_channels: 1038
    rgb_key: ["head_cam", "front_cam"]
    emvis_config:
      load_vggt_pretrain: True
      # 'load_vggt_heads': True
      vggt_model_path: /workspace/RoboticsManipulation/checkpoints/VGGT-1B/model.pt
      mlp_ratio: 1.0
      drop_p: 0.
      ft_layer_idx: []
      intermediate_layer_idx: [4, 11, 17, 23]
      interpolate: 'bicubic'
      injector_config: 
          fuse_2d: False
          ffn_layer_num: 1
      model_adapter_config: 
          shape_out: [1,1]
          dim_out: 512
      mv_fuser_config: 
          view_num: 2
          ffn_layer_num: 1

train_dataset:
  root: /root/data/projects/embodiedai/RoboticsManipulation/RoboticsManipulation/data/lerobot/dual_bottles_pick_hard_D435_drrm
  repo_id: D-robotics/dual_bottles_pick_hard_D435_drrm
  npy_feature_keys: null
  dataset_metadata:
    root: ${train_dataset.root}
    repo_id: ${train_dataset.repo_id}